# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   deploy-production: #############JOB#############
    if: github.ref == 'refs/heads/main'
    name: Deploy - PROD
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2

      - name: Authentication AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.CICDFARGATE_SHAREDSERVICES_ACESSKEY}}
          aws-secret-access-key: ${{secrets.CICDFARGATE_SHAREDSERVICES_SECRETKEY}}
          aws-region: sa-east-1
  
      - name: Build Docker image
        run : |
              docker build -t vxuikit .
              docker tag vxuikit:latest 565724443166.dkr.ecr.sa-east-1.amazonaws.com/vxuikit:latest
      - name: Deploy
        run : |
              aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 565724443166.dkr.ecr.sa-east-1.amazonaws.com             
              docker push 565724443166.dkr.ecr.sa-east-1.amazonaws.com/vxuikit:latest
              aws ecs update-service --cluster vxuikit --service SVC-vxuikit --force-new-deployment
